### ISSUE TITLE
CvsLsorted function duplicated

### ISSUE THREAD

**Issue by De-Cristo** [cms-rwth/VHccPoCo#17]
Hi, noticed that there are CvsLsorted functions in both [CommonSelection](https://github.com/cms-rwth/VHccPoCo/blob/main/CommonSelectors.py#L4-L6) and [pocketcoffea](https://github.com/PocketCoffea/PocketCoffea/blob/main/pocket_coffea/lib/jets.py#L261-L271). There's no conflict error during processing but I am wondering which one will be used and is it okay to keep both functions like this?

**Comment by andreypz** [comment]
I think the one from pocketcoffea is used. And we should remove the other one from our code  to avoid confusion. It was there from the development time, but no longer needed.

**Comment by andreypz** [comment]
Solved by #19
