### ISSUE TITLE
Naming of the datacard histograms

### ISSUE THREAD

**Issue by De-Cristo** [cms-rwth/VHccPoCo#35]
In the shapemake histogram naming ([example](https://github.com/De-Cristo/VHccPoCo/blob/vhbb_dev/params/shapemaker_vhcc_run3/Zll.yaml#L60-L63)),
the name of 2 lepton is confused with 2 light flavor jets:
```
DYJetsToLL_FxFx: "Zj_ll"
DYJetsToLL_FxFx__DiJet_ll: "Zj_ll"
```
This auto matically add the inclusive sample and the light flavor samples together, which increases the DY bkg. The issue could effect the upper limit result badly. we could change it to Zj_inc

**Comment by andreypz** [comment]
I don't think config this affects the scripts.
Once the jet-flavor splitting is used, there is no inclusive sample in the list of histograms,  so there is no `DYJetsToLL_FxFx`  histogram.

That said, we should rename/remove it from the config anyway, to avoid confusion.
